Update VPN instructions for Mac
altcomphsr/altcomphsr.vshsr.ch pull request #105
Opened 2020-01-26 20:36 UTC by backflip

Siehe https://github.com/openhsr/www.openhsr.ch/issues/92

2020-01-27 16:49 UTC, fabianhauser commented
@FunkyFabe könntest du das testen, du hast ja auch einen Mac, oder?

2020-02-28 19:49 UTC, FunkyFabe requested changes
@fabianhauser Was ist deine Meinung bezüglich der «2. Variante»?

Habe es auf meinem Mac (10.15.3 ) getestet und es funktioniert 👍

2020-02-28 19:49 UTC, FunkyFabe commented on _hsr/vpn.md
> +### 1. openconnect installieren
```suggestion
### 1. OpenConnect installieren
```

2020-02-28 19:49 UTC, FunkyFabe commented on _hsr/vpn.md
> +**Variante 2**: Source builden
Meiner Meinung nach sollte die Anleitung so einfach wie möglich sein. Da Homebrew der inoffiziell offizielle Paketmanager für macOS ist, würde ich die 2. Variante entfernen. Es wird zudem auch empfohlen, dies nicht zu machen:

> Unless you need to test the very latest version, you should not need to build OpenConnect for yourself. Your operating system should have a prepackaged version which you can install; if it does not then file a bug or enhancement request asking for one.

Quelle: http://www.infradead.org/openconnect/building.html

2020-02-28 19:49 UTC, FunkyFabe commented on _hsr/vpn.md
> +1. Beim ersten Promt den Benutzernamen eingeben,
```suggestion
Beim ersten Promt den **Benutzernamen**, beim zweiten das **Passwort** und beim dritten den **Code aus der Swivel-App** eingeben.
```

2020-02-29 11:56 UTC, backflip commented
Danke für die Inputs, PR entsprechend angepasst

2020-03-02 16:12 UTC, fabianhauser commented
Kann glaub so gemerged werden @FunkyFabe?

2020-05-29 15:43 UTC, Darnor commented
Hab es eben getestet und funktioniert prima. Vielleicht könnte man noch erwähnen, dass man mittels `brew cask install openconnect-gui`, wie der Name schon sagt, ein GUI bekommt (muss beim ersten starten unter Security & Privacy erlaubt werden).

2020-06-02 08:09 UTC, fabianhauser commented
Möchtest du das noch anpassen @Darnor? Ansonsten bitte gleich mergen, der Pull Request ist irgendwie untergegangen bei uns...

2020-06-04 09:58 UTC, merged