Netzwerklaufwerke einbinden per mount-Befehl
altcomphsr/altcomphsr.vshsr.ch pull request #47
Opened 2016-08-27 10:31 UTC by bytinbit

Mir ist klar, dass das für Anfängerinnen und Anfänger kein einfaches Vorgehen ist.
Aber, und deswegen muss die Anleitung rein: Das Samba-Protokoll ist von Windows, wenn Samba rumspinnt, funktionieren die Netzwerklaufwerke nicht mehr und es gibt keinen Zugriff. Ich erinnere an letztes Semester, als Samba irgendein Update hatte und während einer gewisser Zeit (1 Tag?) die Netzwerklaufwerke nicht mehr über den einfachen Weg eingebunden werden konnten. Was funktionierte, war der Mount-Befehl. Deswegen ist meiner Einschätzung nach die Anleitung zwingend zu erwähnen, aber mit dem Hinweis, dass es für Fortgeschrittene ist.

2016-09-19 07:40 UTC, fabianhauser commented on _hsr/shares.md
> +2. Wechsle ins Verzeichnis ```HSR``` und erstelle dort vier weitere Ordner. Du kannst ihnen irgendeinen Namen geben oder sie folgendermassen benennen:
Ich würde vorschlagen, alle Ordnernamen (HSR, MyShare etc.) alles klein zu schreiben. Da unter Linux die Verzeichnistruktur Case-Sensitive ist, macht das die Navigation deutlich einfacher.

2016-09-19 07:42 UTC, fabianhauser commented on _hsr/shares.md
> +3. Zwar könntest du jeweils von Hand die Verzeichnisse mounten, müsstest aber alle Einzelheiten von Hand eintragen. Deswegen vereinfachen wir den Vorgang. Öffne einen Texteditor. Trage folgende Zeile
Wollen wir diesen Schritt als **Optional** kennzeichnen? Es soll ganz klar ersichtlich sein, dass dies ein Sicherheitsrisiko ist, und alternativ bei jedem Mount das Passwort eingetippt werden kann.

Das Sicherheitsrisiko ist übrigens auch bei verschlüsselten Partitionen z.T. zutreffend: Wenn dein Computer eingeschaltet ist, liegt die Datei unverschlüsselt im RAM.

2016-09-19 07:46 UTC, fabianhauser commented on _hsr/shares.md
> +```$ chmod 400 .fstab.credentials.hsr```<br>
``` chmod 600``` ist auch okay - damit kann das HSR-Passwort ohne erneuten ```chmod``` auch wieder geändert werden :wink:

2016-09-19 07:49 UTC, fabianhauser commented on _hsr/shares.md
> +```$ chmod 400 .fstab.credentials.hsr```<br>
Mit folgendem Konstrukt kannst du direkt Bash-eingaben kennzeichnen:
<pre>
```bash
chmod ...
sudo ...
```
</pre>
Damit wird auch das Copy-Paste einfacher (da kein $ im Text steht, siehe z.B. auch https://www.openhsr.ch/styleguide/#shell)

2016-09-19 08:03 UTC, fabianhauser commented on _hsr/shares.md
> +```//c206.hsr.ch/skripte	/mnt/HSR/Skripte	cifs	credentials=/home/$UBUNTU_USERNAME/.fstab.credentials.hsr,noauto,users,iocharset=utf8  0  0```<br>
Du kannst mit <code>```</code> auch mehrzeiligen Code (inklusive Zeilenumbrüche) erstellen

2016-09-19 08:10 UTC, fabianhauser commented on _hsr/shares.md
> +```//c206.hsr.ch/skripte	/mnt/HSR/Skripte	cifs	credentials=/home/$UBUNTU_USERNAME/.fstab.credentials.hsr,noauto,users,iocharset=utf8  0  0```<br>
Bei den Readonly-Mounts könnte zur Verdeutlichung noch das ```ro``` Flag hinzugefügt werden.

2016-09-19 08:14 UTC, fabianhauser commented on _hsr/shares.md
> +```//c206.hsr.ch/skripte	/mnt/HSR/Skripte	cifs	credentials=/home/$UBUNTU_USERNAME/.fstab.credentials.hsr,noauto,users,iocharset=utf8  0  0```<br>
Bei allen Mounts würde ich noch ```soft``` dazuschreiben (stellt sicher, das bei Verbindungsfehlern ein richtiger i/o-Fehler ausgelöst wird. Bei ```hard``` wird angenommen, dass es "keinen" Paketverlust gibt - etwas optimistisch beim HSR-WLAN :wink:)

2016-09-19 08:23 UTC, fabianhauser commented on _hsr/shares.md
> +Schreibe anstelle ```$UBUNTU_USERNAME``` deinen Login-Namen, mit dem du dich in Ubuntu einloggst. Ersetze ```$HSR_USERNAME``` mit dem Login-Namen, den du für die HSR verwendest.<br>
Gemäss [Styleguide](https://www.openhsr.ch/styleguide/#kurzum]) probieren wir jeweils, als HSR-Benutzernamen ```mmuster``` und als lokalen Benutzer ```maria``` zu nehmen, dies ist jeweils etwas übersichtlicher als mit Variablen (aber etwas weniger praktisch im Copy-Paste, das stimmt :blush:)

2016-09-19 08:23 UTC, fabianhauser requested changes
Hey @bytinbit, ich habe im Diff noch ein paar Verbesserungsvorschläge ergänzt!

LG Fabian

2016-10-04 12:21 UTC, bytinbit commented
Frage zur Darstellung: Die aktuelle Darstellung führt zu Problemen, wenn man sehr lange Zeilen hat. Was ist da die Konvention?

Dargestellt sollte Folgendes alls auf einer Zeile:
"//c206.hsr.ch/ebooks 	/mnt/hsr/ebooks		cifs	credentials=/home/maria/.fstab.credentials.hsr,noauto,users,iocharset=utf8,soft,ro  0  0"

Darstellungsweise in Markdown:
```
//c206.hsr.ch/ebooks 	/mnt/hsr/ebooks		cifs	credentials=/home/maria/.fstab.credentials.hsr,noauto,users,iocharset=utf8,soft,ro  0  0
```

==> stellt es auf einer Zeile dar, Zeileninhalt verschwindet aber in Hintergrund, siehe Bild.

![largeline](https://cloud.githubusercontent.com/assets/20699009/19073893/c4725460-8a3d-11e6-864c-fd36f7bcf3af.png)

Wie lösen wir das Problem?

2016-10-04 12:29 UTC, bytinbit commented
Der ```-Befehl für Code-Zeilen zerschiesst offenbar die automatische Nummerierung der Liste. Gibt es da einen Fix? Das Problem ist bei allen Listeneinträgen ab folgendem Punkt vorhanden:
`
3. **Optional:** Du kannst jeweils von Hand die Verzeichnisse mounten, müsstest aber alle Einzelheiten von Hand eintragen. Deswegen vereinfachen wir den Vorgang. Öffne einen Texteditor. Trage folgende Zeilen ein:

```bash
username=mmuster
password=GeHeim007
``` 

Speichere die Datei in deinem Home-Verzeichnis unter dem Namen ```.fstab.credentials.hsr```. Vergiss den Punkt zu Beginn der Datei nicht!

4. Setze die Zugriffsrechte für die Datei, damit niemand ausser dir darauf zugreifen kann. Öffne ein Terminalfenster und tippe:
`

2016-10-04 14:33 UTC, raphiz commented
@bytinbit die zu Langen Zeilen müssen wir mit eine Scrollbar lösen (CSS Property overflow-y: auto)
Zur Nummerierung: Eventuell nützt einrücken etwas?

2016-10-04 15:09 UTC, bytinbit commented
Ja, einrücken hat geklappt => habs in den entsprechenden Anleitungen / Cheatsheets nirgends erwähnt gefunden... :-/ danke! wird gleich committed.

2016-10-04 16:18 UTC, raphiz commented
@bytinbit habe das Issue mit zu wenig Platz in Master-Branch gefixt (a3403b8 ) - musst dich also nicht mehr darum kümmern

2016-10-04 16:28 UTC, raphiz requested changes
Super, Herzlichen Dank :tada: :balloon: !

Habe noch ein paar kleine Änderungen vorgeschlagen.

2016-10-04 16:28 UTC, raphiz commented on _hsr/shares.md
> +
Ich wäre froh, wenn wir hier noch einen kleinen Hinweis machen würden, dass dies keine gute Idee ist, wenn die Festplatte bzw. das User-Home nicht Verschlüsselt ist (Ein Geschenk bei einer Offline-Attacke)

2016-10-04 16:28 UTC, raphiz commented on _hsr/shares.md
> + * ```ebooks``` - Ältere und neuere Ebooks
Wäre cool, wenn du ebooks auch oben unter "Pfade zu den HSR Netzwerkfreigaben" hinzufügen würdest (war mir bisher nicht bekannt :laughing: )

2016-10-04 16:28 UTC, raphiz commented on _hsr/shares.md
> + * ```skripte``` - Skripte aller Studiengänge
Ich würde das hier kürzen - ist ja mehr oder weniger identisch zu den Ordnern unter "Pfade zu den HSR Netzwerkfreigaben". Um konsistent zu "Netzwerkfreigaben unter Ubuntu einrichten" bleiben würde ich es an einem einzelnen Beispiel (bsp. Skripteserver oder userhome) durcharbeiten. Oder hast du aus einem bestimmten Grund alle reingenommen?

2016-10-05 10:56 UTC, raphiz approved these changes

2016-10-05 11:01 UTC, raphiz commented
@fabianhauser kannst du bitte dein Review approven bzw. aktuallisiern? Dann können wir hier mergen

2016-10-05 12:03 UTC, fabianhauser approved these changes

2016-10-05 12:05 UTC, merged