New Tipp: Microsoft Imagine added
altcomphsr/altcomphsr.vshsr.ch pull request #55
Opened 2016-09-19 07:08 UTC by michiwieland

Der Link zu Microsoft Imagine ist schwer zu finden und sollte über unser Wiki auffindbar sein. Besonders relevant für VM's und für die Entwicklung mit Visual Studio.

2016-09-19 07:27 UTC, fabianhauser commented on tipps/_posts/2016-09-19-microsoft-imagine.md
> +Microsoft stellt allen Studierenden einige ihrer Produkte frei zur Verfügung. Für den Unterricht sind besonders Visual Studio 10, sowie das aktuelle Windows 10 von Relevanz.
Ich würde statt *frei* => *kostenlos* schreiben, sowie *Closed Source Produkte* schreiben, damit keine Missverständnisse aufkommen.

2016-09-19 07:31 UTC, fabianhauser commented on tipps/_posts/2016-09-19-microsoft-imagine.md
> +Alle zur Verfügung stehenden Produkte können hier bestellt und heruntergeladen werden:
Link könnten wir auf die gleiche Zeile verschieben?

2016-09-19 07:31 UTC, fabianhauser requested changes

2016-09-19 07:32 UTC, raphiz commented
@michiwieland cool - was hälst du davon, wenn wir das ganze etwas "parteiischer" formulieren?
Also a la: Für gewisse Module wie MsTec braucht man Windows oder eine Microsoft Software - etwas was wir nicht mit alternativen fixen können. Aber es gibt immerhin Dreamspark....

2016-09-19 12:25 UTC, michiwieland commented
Ich habe die Formulierung gemäss euren Inputs ein wenig angepasst :) Weitere ergänzungen dürft ihr meinetwegen gerne selber kurz machen.

2016-09-20 13:10 UTC, fabianhauser approved these changes

2016-09-20 13:11 UTC, merged