Neuer Tipp: Wine und DASYLab
altcomphsr/altcomphsr.vshsr.ch pull request #57
Opened 2016-10-04 07:53 UTC by seboschtion

Manche Programme kann man mit Wine ausführen, dann muss man nicht immer eine VM verwenden. Ich dachte, eine kurze Anleitung dazu wäre praktisch... Was meint ihr?

2016-10-04 08:31 UTC, bytinbit commented
DASYLab kannte ich nicht, sicher ein Tipp wert.
Wine: Die Installation und Verwendung ist denkbar einfach, kennen Einsteigerinnen und Einsteiger vielleicht nicht. Wissen um Wine kann die Angst nehmen "aber mit Linux funktionieren alle meine Windows-Programme nicht mehr!!11!!"

Deshalb: Wine- und DasyLab-Tip +1

Vorschlag: Sektion "Aber ich brauche Programm X vom anderen OS trotzdem, was kann ich tun?"
=> Möglichkeiten: VM (=> VirtualBox, VMPlayer), Wine mit je kurzen Tipps/Hinweisen

2016-10-04 11:18 UTC, raphiz commented
@bytinbit Ich finde dein Vorschlag gut! Die Frage `Aber ich brauche Programm X vom anderen OS trotzdem, was kann ich tun?` kommt in die FAQ - und DasyLab (mit Hinweis auf welches Modul) als Tipp!
Coole sache :tada:

2016-10-04 15:55 UTC, fabianhauser requested changes
Vielen Dank @seboschtion für den Pull-Request!
Ich habe noch ein paar Kommentare im Diff reingeschrieben. Zudem finde ich auch, dass er besser in die Kategorie Tipps passt.

Evtl. wäre es noch eine Idee, am Anfang einen Disclaimer im Sinne von: "Nicht alle Programme laufen unter Wine sauber (MS Office etc.)." und "Mit Wine laufen neu auch alle Windows Viren auf Linux!" zu ergänzen? :wink:

2016-10-04 15:55 UTC, fabianhauser commented on _app/wine.md
> +sudo wine setup.exe
So weit ich mich erinnere, muss der Setup ohne ```sudo``` ausgeführt werden (die ganze Ordnerstruktur ist ja im Homeverzeichnis), oder?

2016-10-04 15:55 UTC, fabianhauser commented on _app/wine.md
> +Leider nicht. Welche Programme fehlerfrei, welche nur teilweise und welche gar nicht funktioneren ist schwierig festzuhalten. Die untenstehende Liste ist für Programme gedacht, welche keine Linux-fre
Wollen wir hier noch als alternative VMs erwähnen?

2016-10-04 15:55 UTC, fabianhauser commented on pages/app.md
> +DASYLab			| keine / Verwendung mit [Wine](/app/wine#dasylab) 	| -
Hier wäre der Modulname noch gut :)

2016-10-07 08:44 UTC, seboschtion commented
Super, danke für eure Kommentare! Also verschiebe ich einfach alles zu den Tipps? Deine Änderungen werde ich natürlich auch noch übernehmen, @fabianhauser, finde ich gut.

2016-10-07 08:47 UTC, raphiz commented
@seboschtion Ja genau.
Super wäre, wenn du den Vorschlag von @bytinbit ("Aber ich brauche Programm X vom anderen OS trotzdem, was kann ich tun?") in die FAQ übernehmen würdest.

2016-10-10 07:04 UTC, seboschtion commented
Habe die Änderungen gemacht, was meint ihr dazu? :-)

2016-10-10 07:29 UTC, raphiz commented
@seboschtion Für mich super! Btw, du kannst Emojis verwenden - anstatt :-) mit `:smile:` :smile: oder `:smiley:` :smiley:   

Wenn Fabian sein OK gibt können wir das mergen! Herzelichen Dank!

2016-10-12 12:44 UTC, fabianhauser approved these changes

2016-10-12 12:57 UTC, merged