added printer configuration for MFP-BW
altcomphsr/altcomphsr.vshsr.ch pull request #96
Opened 2019-04-29 11:25 UTC by MarcusMoeller

2019-04-29 11:36 UTC, The-Compiler approved these changes
Habs nicht ausprobiert, aber sieht gut aus - danke @MarcusMoeller! :+1:

2019-04-29 13:27 UTC, fabianhauser requested changes
Funktioniert bei mir (bis auf das fehlende `.ppd`) einwandfrei, danke @MarcusMoeller!

Evtl. würde es Sinn machen, die Farbdrucker auch noch zu ergänzen?  
Soweit ich sehe:
- `MFP-Color`
- `Canon iR-ADV C5550/5560 III UFR II`
- `CNCUPSIRADVC55503ZK.ppd`

2019-04-29 13:27 UTC, fabianhauser commented on _hsr/printing.md
> +-m CNCUPSIRADV85853ZK
Ich muss bei dieser Zeile noch den vollständigen Dateinahmen angeben: `-m CNCUPSIRADVC55503ZK.ppd`

2019-04-29 13:51 UTC, MarcusMoeller commented on _hsr/printing.md
> +-m CNCUPSIRADV85853ZK
Pushe es erstmal so. Ich würde bei Gelegenheit (also dann wenn ich es selbst brauche ;)) den MFP-Color adden. Mache dann einen neuen MR auf.

2019-04-30 09:19 UTC, fabianhauser approved these changes

2019-04-30 09:19 UTC, merged

2019-04-30 09:19 UTC, fabianhauser commented
👍